import Head from 'next/head';
import Link from 'next/link';
import styles from '@/styles/Home.module.css';
import { getSortedPostsData } from '../lib/posts';
import Layout from '@/components/layout';
import utilStyles from '@/styles/utils.module.css';


export async function getStaticProps() {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
}

export default function Home() {
  return (
    <Layout home>
      <Head>
        <title>Yubi Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <section className={utilStyles.headingMd}>
          <p>
            I am a passionate Full Stack Developer. I eat Nodejs, React, Graphql
            and AWS.{' '}
          </p>
        </section>
        <h3>
          Read my first post <Link href="/posts/first-post">here</Link>
        </h3>
      </main>
    </Layout>
  );
}
